# Generated by Django 4.1.1 on 2022-10-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_age_user_fb_profile_link_user_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "An user with this email already exists"},
                max_length=254,
                unique=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "MALE"), (1, "FEMALE"), (2, "OTHER")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                error_messages={
                    "unique": "An user with this phone number already exists"
                },
                max_length=11,
                unique=True,
                verbose_name="Phone",
            ),
        ),
    ]
