# Generated by Django 4.1.1 on 2023-01-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='diagram',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/projects/diagrams/'),
        ),
    ]
