# Generated by Django 4.1.1 on 2023-01-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.TextField(choices=[('DATE BOOKED', 'DATE BOOKED'), ('DRAFT', 'DRAFT'), ('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], default='DATE BOOKED'),
        ),
    ]
