# Generated by Django 4.1.1 on 2022-10-06 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_schedule_test_bed_alter_schedule_unique_together"),
        ("project_management", "0003_remove_project_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schedules.schedule",
            ),
        ),
    ]
