# Generated by Django 4.1.1 on 2023-01-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_project_diagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='extra_instruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
