# Generated by Django 4.1.1 on 2023-01-16 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_alter_tool_created_at_alter_tool_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0004_project_extra_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='test_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.testbed'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('test_bed', 'owner')},
        ),
    ]
