# Generated by Django 4.1.1 on 2023-01-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0005_project_test_bed_alter_project_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.TextField(choices=[('DATE BOOKED', 'DATE BOOKED'), ('DRAFT', 'DRAFT'), ('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], default='PENDING'),
        ),
    ]
