# Generated by Django 4.1.1 on 2023-01-22 17:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Test Bed Name')),
                ('cam_feed_link', models.TextField(blank=True, max_length=2050, null=True, verbose_name='Live cam feed link')),
                ('specs', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Test Bed',
                'verbose_name_plural': 'Test Beds',
                'db_table': 'test_beds',
            },
        ),
        migrations.CreateModel(
            name='ToolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tool Type Name')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Tool Type',
                'verbose_name_plural': 'Tool Types',
                'db_table': 'tool_types',
            },
        ),
        migrations.CreateModel(
            name='WidgetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Widget Type Name')),
                ('specs', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Widget Type',
                'verbose_name_plural': 'Widget Types',
                'db_table': 'widget_types',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tool Name')),
                ('quantity', models.IntegerField(default=1)),
                ('user_values', models.JSONField(blank=True, default=dict, null=True)),
                ('mqtt_data', models.JSONField(blank=True, default=dict, null=True)),
                ('specs', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('type', models.ForeignKey(error_messages={'null': 'Tool Type is required'}, on_delete=django.db.models.deletion.CASCADE, to='tools.tooltype')),
                ('widget_type', models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='tools.widgettype')),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'db_table': 'tools',
            },
        ),
    ]
