# Generated by Django 4.1.1 on 2022-10-04 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tooltype",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tooltype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Tool Name"
                    ),
                ),
                ("specs", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "type",
                    models.ForeignKey(
                        error_messages={"null": "Tool Type is required"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tools.tooltype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tool",
                "verbose_name_plural": "Tools",
                "db_table": "tools",
            },
        ),
    ]
