# Generated by Django 4.1.1 on 2023-01-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Widget Type Name')),
                ('specs', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Widget Type',
                'verbose_name_plural': 'Widget Types',
                'db_table': 'widget_types',
            },
        ),
        migrations.AddField(
            model_name='tool',
            name='widget_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='tools.widgettype'),
        ),
    ]
