# Generated by Django 4.1.1 on 2022-10-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0002_alter_tooltype_created_at_alter_tooltype_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestBed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Test Bed Name"
                    ),
                ),
                ("specs", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Test Bed",
                "verbose_name_plural": "Test Beds",
                "db_table": "test_beds",
            },
        ),
    ]
