# Generated by Django 4.1.1 on 2023-01-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_widgettype_tool_widget_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgettype',
            name='specs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
