# Generated by Django 4.1.1 on 2023-01-13 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_tooltype_created_at_alter_tooltype_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='tool',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='widgettype',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='widgettype',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
