# Generated by Django 4.1.1 on 2023-01-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_alter_tool_created_at_alter_tool_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbed',
            name='cam_feed_link',
            field=models.TextField(blank=True, max_length=2050, null=True, verbose_name='Live cam feed link'),
        ),
    ]
