# Generated by Django 4.1.1 on 2023-01-13 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(default=None, error_messages={'blank': 'Starting time can not be empty'})),
                ('end_time', models.TimeField(default=None, error_messages={'blank': 'Ending time can not be empty'})),
                ('is_available', models.BooleanField(default=True)),
                ('test_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.testbed')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'schedules',
                'unique_together': {('date', 'start_time', 'end_time', 'test_bed')},
            },
        ),
    ]
