# Generated by Django 4.1.1 on 2022-10-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "start_time",
                    models.TimeField(
                        default=None,
                        error_messages={"blank": "Starting time can not be empty"},
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        default=None,
                        error_messages={"blank": "Ending time can not be empty"},
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Schedule",
                "verbose_name_plural": "Schedules",
                "db_table": "schedules",
            },
        ),
    ]
