# Generated by Django 4.1.1 on 2023-01-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(error_messages={'blank': 'Starting time can not be empty'})),
                ('end_time', models.TimeField(error_messages={'blank': 'Ending time can not be empty'})),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'schedules',
                'unique_together': {('date', 'start_time', 'end_time')},
            },
        ),
    ]
