# Generated by Django 4.1.1 on 2022-10-06 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0003_testbed"),
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="test_bed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tools.testbed",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="schedule",
            unique_together={("date", "start_time", "end_time", "test_bed")},
        ),
    ]
